language: en
lang_direction: ltr
landing_page:
  welcome_message:
    text: 'Bem vindo a G Party do Hackday!'
  name_form:
    text: 'Insira seu nome para participar da transmissão!'
    name_placeholder_text: Nome
    password_placeholder_text: Senha da sala
    submit_button_text: Enviar
navbar:
  title:
    text: G Party Hackday
text_chat:
  submit_button_text: Enviar
  placeholder_text: 'Insira sua mensagem aqui'
